### ISSUE TITLE
GuzzleHttp\Client

### ISSUE THREAD

**Issue by melusinenesmlp** [neolikotsi/php-smsportal#2]
Fatal error: Uncaught Error: Class 'GuzzleHttp\Client' not found in C:\xampp\htdocs\SMS\neolikotsi\smsportal\src\RestClient.php:31 Stack trace: #0 C:\xampp\htdocs\SMS\Index.php(13): NeoLikotsi\SMSPortal\RestClient->__construct('....', '...', 'https://rest.sm...') #1 {main} thrown in C:\xampp\htdocs\SMS\neolikotsi\smsportal\src\RestClient.php on line 31

**Comment by neolikotsi** [comment]
Hi @melusinenesmlp update to release 1.0.10

**Comment by melusinenesmlp** [comment]
Thanks Neo,

I had already resolved this, Now I want to Ask:


$responseArray1 = $client->message()->send([
                    'messages' => [
                        [
                            'destination' => '+26878110252',
                            'content' => $message->getContent(),
                        ]
                    ]
                ]);


To add multiple recipients of the same message how do I do that?

**Comment by neolikotsi** [comment]
you can append '**messages**' array to send more messages in the same request. Remember to keep to the bulk size that the docs specify as the limit for 1 request. 

`
$content = $message->getContent();
`
```php
...
'messages' => [ 
  [
    'destination' => '1234567890',
    'content' => $content,
  ],
  [
    'destination' => '0123456789',
    'content' => $content,
  ],
]
```

**Comment by melusinenesmlp** [comment]
Thanks

**Comment by melusinenesmlp** [comment]
Hi Neo,

Please assist, I want to push SMS replies from smsportal.com into mysql database.
