### ISSUE TITLE
SMS Replies to MySQL

### ISSUE THREAD

**Issue by melusinenesmlp** [neolikotsi/php-smsportal#3]
Please assist, I want to push SMS replies from smsportal.com into mysql database.

**Comment by neolikotsi** [comment]
Hi Melusi, inbound SMSes are not part of the package. Have a look at the [smsportal docs](https://docs.smsportal.com/docs/webhooks-rest) to see how to add a webhook to your application.

**Comment by melusinenesmlp** [comment]
I’ve tried and failed.
